### ISSUE TITLE
Feature Request: Javascriptlet for Browsers

### ISSUE THREAD

**Issue by helmut72** [podify-org/podify#11]
It would be easier to add a video with a Javascriptlet instead of copy/paste the URLs. Thank you!

**Comment by maxhollmann** [comment]
When you update to `maxhollmann/podify-web:preview`, next to the feeds in the menu you'll find a settings icon now, and in there's a bookmarklet you can drag&drop to the toolbar. Let me know how that works for you!

**Comment by helmut72** [comment]
Thanks, works!! A lot easier than copy/paste 👍
