### ISSUE TITLE
Fully-contained docker image

### ISSUE THREAD

**Issue by reesericci** [podify-org/podify#17]
It would be cool if you guys could make the current docker image contain Redis and Postgres in one complete image.

**Comment by maxhollmann** [comment]
That's not really the way docker is intended to be used (see https://docs.docker.com/config/containers/multi-service_container/).
What's your use case for this? Take a look at the [docker-compose.example.yml](https://github.com/podify-org/podify/blob/master/docker/docker-compose.example.yml) for how to run the whole thing using docker-compose.

**Comment by reesericci** [comment]
I want to run it in k8s and don't want a ton of containers for one service. I think it would be cool if you guys had both available, as if I was already running Redis and Postgres, then that would be great. It would be useful to some people like me.

**Comment by reesericci** [comment]
@maxhollmann

**Comment by BadCo-NZ** [comment]
I would like to run this on unRAID with minimal complexity, so one container would be easier.

**Comment by reesericci** [comment]
I don't use redis, I don't use postgres, if I did I could drop this in. But I don't, and a lot of other people don't, and a simple container would be useful.

**Comment by borgmanJeremy** [comment]
Whether you run redis and Postgres in one container or in many containers you must still run those services. 

The current compose model is much more standard and IMO  it provides an easy setup with plenty of flexibility.

**Comment by BadCo-NZ** [comment]
> Whether you run redis and Postgres in one container or in many containers you must still run those services.
> 
> The current compose model is much more standard and IMO it provides an easy setup with plenty of flexibility.

Which is fine, if you can use docker-compose.

Unfortunately unRAID dies not :( well, there might be a way to do it that I'm not aware of yet.

**Comment by borgmanJeremy** [comment]
Ohhhhhh ok

Maybe this will work? https://forums.unraid.net/topic/91436-is-docker-compose-available-on-unraid/

**Comment by reesericci** [comment]
I don't use docker-compose either, I use Kubernetes.

**Comment by reesericci** [comment]
@maxhollmann any comments?

**Comment by maxhollmann** [comment]
Well, I won't work on a single-container Dockerfile myself as there are many things with higher priority on my todo list. Like borgmanJeremy said, you're running all three services either way, the only difference running it in a single container makes is that errors become both more likely and less transparent. I'm open to pull requests though if you or someone else wants to work on this, as @BadCo-NZ' seems to have a valid usecase for it.

**Comment by BadCo-NZ** [comment]
> Ohhhhhh ok
> 
> Maybe this will work? https://forums.unraid.net/topic/91436-is-docker-compose-available-on-unraid/

Yeah I figured there would be a way to script it to make it persistent.

**Comment by BadCo-NZ** [comment]
> Well, I won't work on a single-container Dockerfile myself as there are many things with higher priority on my todo list. Like borgmanJeremy said, you're running all three services either way, the only difference running it in a single container makes is that errors become both more likely and less transparent. I'm open to pull requests though if you or someone else wants to work on this, as @BadCo-NZ' seems to have a valid usecase for it.
> 
> I'm currently experimenting with Kubernetes though, so I might provide a sample Kubernetes config sometime soon, though still running the three services in separate containers ;)

Thanks for the reply @maxhollmann 

I'm not that familiar with postgres and DBs in general, but is there a way to use another DB like MariaDB so we don't need to double up on Databases? Or does postgres do something special?

**Comment by maxhollmann** [comment]
> I'm not that familiar with postgres and DBs in general, but is there a way to use another DB like MariaDB so we don't need to double up on Databases? Or does postgres do something special?

No, that won't work unfortunately, the app is using Postgres' [jsonb](https://www.postgresql.org/docs/9.4/datatype-json.html) type.
