### ISSUE TITLE
Trouble with db after disk full issue

### ISSUE THREAD

**Issue by metasikander** [podify-org/podify#23]
i started a download to podify, but the disk i was using didn't have enough space so it never finished.
i moved the container to another machine with more space, but if i try to download the same video i get a "request.create.error".
![image](https://user-images.githubusercontent.com/2529307/106011963-43592a80-60bb-11eb-94bc-adaac8239c82.png)
the video is not in the list.
i guess there is a missmatch between the db and the frontend, but i'm not sure how to best fix this.

**Comment by metasikander** [comment]
log from web-container:
```
D, [2021-01-27T15:21:45.875654 #1] DEBUG -- : [aeaa159f-8a37-4995-bf83-91c37eeed54a] PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "requests_user_id_source_id_index"
DETAIL:  Key (user_id, source_id)=(1, 42) already exists.
 excluded from capture: DSN not set
F, [2021-01-27T15:21:45.876328 #1] FATAL -- : [aeaa159f-8a37-4995-bf83-91c37eeed54a]   
[aeaa159f-8a37-4995-bf83-91c37eeed54a] Sequel::UniqueConstraintViolation (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "requests_user_id_source_id_index"
DETAIL:  Key (user_id, source_id)=(1, 42) already exists.
):
```

**Comment by maxhollmann** [comment]
The frontend doesn't retain state between reloads, so a mismatch there is unlikely.

I guess the easiest fix for this would be to start with a fresh DB. Since the downloads from the old DB won't be available anyways you're not really using data... Let me know if that's not possible for you and I can look into a less nuclear option ^^

**Comment by metasikander** [comment]
okay. i would like to keep the db, as everything works as expected except for that one video.
i would prefer to not mess up peoples rss-feed with a reset.
so if you have a simple way to fix this then i would highly appreciate it 😊

**Comment by metasikander** [comment]
that did something. i don't get the error anymore, but it still won't download the video.
it just stays at "pending" and if i reload the page it's gone.

i appreciate the help you're giving me here, but it's not that big of a problem if you want to focus on something else. i can download videos from other sources, so i can find a way around it. 😊

**Comment by maxhollmann** [comment]
If only some sources don't download that's probably a problem with youtube-dl, I can't do much about that.
