### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Orilcious** [podify-org/podify#24]
Hello,

I was trying to setup podify using docker/docker-compose.example.yml on localhost and got ERR_SSL_PROTOCOL_ERROR in both firefox and chromium. Any idea how to fix this?

I can provide worker logs if needed.

Kind regards,
Ori

**Comment by maxhollmann** [comment]
Closing since this is so old, if you still have this problem feel free to reopen!
