### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by FihlaTV** [podify-org/podify#29]
Hi 
I am trying to set up the docker container and run it. Currently, I used the default example yalm config. I am stuck in authentication error, no matter how I try to replace and change passwords of podify user.
Here is my log
2021-05-03 03:31:07.951 UTC [53] FATAL:  password authentication failed for user "podify"
db_1      | 2021-05-03 03:31:07.951 UTC [53] DETAIL:  Password does not match for user "podify".
db_1      | 	Connection matched pg_hba.conf line 95: "host all all all md5"
web_1     | Error: Sequel::DatabaseConnectionError: PG::ConnectionBad: FATAL:  password authentication failed for user "podify"

**Comment by maxhollmann** [comment]
Can you paste the docker-compose.yml you're using, and how you're starting it up?
