### ISSUE TITLE
automatively choosen youtube-dl Version too old

### ISSUE THREAD

**Issue by devnope** [podify-org/podify#35]
I just tried to get podify up and running. Yet I noticed, that youtube links haven't been working.
It appears, that the reason was the version of youtube-dl was too old.

It appears, that the installer inside the podify_worker installed youtube_dl in version `2020.6.6`. I updated the version with `pip3 install -U youtube-dl` to `2021.5.16`.

Maybe it would be helpful to add the -U into the dockerfile or alternatively could it be helpful to hardcode the youtube-dl version for the Python package?

**Comment by glor** [comment]
I created a merge request for that: #38

**Comment by maxhollmann** [comment]
This should only be the case for up to an hour after first starting podify (see #39).

If you search the logs of the worker pod for `UpgradeYoutubeDlJob` you should find something like this:
```
[worker-84769b4486-sg4gt podify]  2021-07-21T07:06:00.119Z pid=1 tid=gih INFO: queueing UpgradeYoutubeDlJob (upgrade_youtube_dl)
[worker-84769b4486-sg4gt podify]  2021-07-21T07:06:00.121Z pid=1 tid=id5 class=UpgradeYoutubeDlJob jid=a07f0f5bf3fea138fddf6ad0 INFO: start
[worker-84769b4486-sg4gt podify]  2021-07-21T07:06:01.606Z pid=1 tid=id5 class=UpgradeYoutubeDlJob jid=a07f0f5bf3fea138fddf6ad0 elapsed=1.485 INFO: done
```
Can you check if that's the case?
