### ISSUE TITLE
Redis update message spam

### ISSUE THREAD

**Issue by Jacob-Evans** [podify-org/podify#40]
`Redis#exists(key)` will return an Integer in redis-rb 4.3, if you want to keep the old behavior, use `exists?` instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer = true. (/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/launcher.rb:160:in `block (2 levels) in ❤')

**Comment by maxhollmann** [comment]
This is solved on the latest docker images.
