### ISSUE TITLE
high memory usage and zombie processes

### ISSUE THREAD

**Issue by helmut72** [podify-org/podify#48]
Frequently need to docker-compose down+up ...

<img width="660" alt="Bildschirmfoto 2021-11-14 um 14 37 59" src="https://user-images.githubusercontent.com/1388751/141683590-c44163e0-d631-4b4b-8bd9-3751e5634d19.png">

<img width="815" alt="Bildschirmfoto 2021-11-14 um 14 36 38" src="https://user-images.githubusercontent.com/1388751/141683608-542d8054-a581-44ad-85ce-f06b6a079a0a.png">

**Comment by helmut72** [comment]
After restarting there are no Zombies because it's just started, but still an huge memory consumption. It's in standby, no downloading or streaming.

<img width="801" alt="Bildschirmfoto 2021-11-14 um 14 51 25" src="https://user-images.githubusercontent.com/1388751/141684128-fa9e7333-d942-42cc-b87d-adce01428519.png">

**Comment by kymodoke** [comment]
Yeah, same here: hundreds of Megs of Ram used by both web and worker while idle... plus a 2.2 GB image size. That way is too much for me.

**Comment by helmut72** [comment]
Looks like memory is needed. Since months even no answer.
