### ISSUE TITLE
Default Admin Account & Credentials 

### ISSUE THREAD

**Issue by NX211** [podify-org/podify#5]
When deploying via Docker is there a default admin account that should be used ? Your .env doesn't seem to allow for setting defaults and I didn't spot anything in the dockerfiles. 
Awesome app by the way.

**Comment by maxhollmann** [comment]
No, and there's also no concept of an admin account yet. You can just sign up as a normal user once the app is running.

As a first step I'll allow creating an initial user via environment variables and allow you to disable the sign up as well. Eventually there will be admin users that can invite others.

Good that you remind me, and glad you like it! :)

**Comment by NX211** [comment]
Awesome. That was exactly what I was thinking. Figured I would open an issue to see where you wanted the project to go. Awesome project, I'll defiantly be following it.

**Comment by maxhollmann** [comment]
You can now configure this via `INITIAL_USER_EMAIL`, `INITIAL_USER_PASSWORD`, and `ENABLE_SIGNUP` (see https://www.podify.org/docker.html).
