### ISSUE TITLE
Website docker-compose example breaks startup

### ISSUE THREAD

**Issue by FrozenDragoon** [podify-org/podify#50]
The `docker-compose` example on website https://www.podify.org/docker.html contains a typo that breaks startup with the error listed in #45 .

The website shows 
```
 worker:
    <<: *app-defaults
    image: maxhollmann/podify:latest
    command: start-server
    environment:
      <<: *app-env
```

Whereas the repo (correctly) shows
https://github.com/podify-org/podify/blob/9553dc44b32082a14e69de41866dbc9fd41d441e/docker/docker-compose.example.yml#L33-L38

After replacing "start-server" with "start-worker", startup completed without issue.

**Comment by codefaux** [comment]
Good news, it's not fixed yet. Seems like a really, really, really, really, really easy fix. Seriously guys it's January. NOT a great user experience so far.

**Comment by maxhollmann** [comment]
It's fixed now.
