### ISSUE TITLE
Tagline is blatantly incorrect

### ISSUE THREAD

**Issue by codefaux** [podify-org/podify#51]
"Create podcasts from anything youtube-dl can handle"

I spent two hours figuring out why your Docker instructions from your website wouldn't work, to find that it was an issue reported here back in November. I fixed that, and fought with other issues, to get it to run.

Podify seemingly will not support "anything" youtube-dl can handle. Podify won't support a Youtube playlist, for example. Youtube-DL supports playlists. Podify does not support playlists, or this functionality is broken. This seems to be something most folks would like at some point, and definitely feels implied with "anything youtube-dl can handle" -- given that Youtube-DL can DEFINITELY handle playlists. Like, natively, quickly, easily, and by default. Please be more clear, if this wasn't an intended inclusion.

Here's the URL I was attempting to use.

https://www.youtube.com/playlist?list=UUBbnbBWJtwsf0jLGUwX5Q3g

If playlist support is not in the immediate future, please inform me so I can find a working solution.

**Comment by maxhollmann** [comment]
It is a planned feature, but I cannot give an estimate when I will get around to working on it as this project isn't my top priority currently. Don't expect it anytime soon.

**Comment by codefaux** [comment]
Do you plan to continue to mislead potential users of your software until then?
